export const types = {
    SET_EMPRESA: 'SET_EMPRESA',
    CLEAR_EMPRESA: 'CLEAR_EMPRESA',
    SET_EMPRESAS: 'SET_EMPRESAS',
    CLEAR_EMPRESAS: 'CLEAR_EMPRESAS',
    SET_CREDENCIAIS_TEMP: 'SET_CREDENCIAIS_TEMP',
    CLEAR_CREDENCIAIS_TEMP: 'CLEAR_CREDENCIAIS_TEMP',
}

