export const types = {
    VALIDAR_LOGIN: 'VALIDAR_LOGIN',
    REALIZAR_LOGIN: 'REALIZAR_LOGIN',
    SET_USUARIO: 'SET_USUARIO',
    DESLOGAR_USUARIO: 'DESLOGAR_USUARIO',
    CLEAR_USUARIO: 'CLEAR_USUARIO',
    LOGIN_ERROR: 'LOGIN_ERROR',
};